sudo: required
services:
  - docker

before_install:
  - docker build -t socialcore/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run socialcore/react-test npm run test -- --coverage

after_success:
  - docker build -t socialcore/multi-docker-client ./client
  - docker build -t socialcore/multi-docker-nginx ./nginx
  - docker build -t socialcore/multi-docker-server ./server
  - docker build -t socialcore/multi-docker-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker
  - docker push socialcore/multi-docker-client
  - docker push socialcore/multi-docker-nginx
  - docker push socialcore/multi-docker-server
  - docker push socialcore/multi-docker-worker
  
